package david_diaz_lab8;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Main extends javax.swing.JFrame {
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDCrear_Contacto = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFNumero_Te = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFDireccion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRBM = new javax.swing.JRadioButton();
        jRBF = new javax.swing.JRadioButton();
        jBGGen = new javax.swing.ButtonGroup();
        jDModificar_Contacto = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFEdad1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRBM1 = new javax.swing.JRadioButton();
        jRBF1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTFNumero_Te1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFCorreo1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFDireccion1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jCBModificar_Contacto = new javax.swing.JComboBox<>();
        jDEliminar_Contacto = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jCBEliminar_Contacto = new javax.swing.JComboBox<>();
        jDAgenda_Contacto = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        arbolito = new javax.swing.JTree();
        jButton6 = new javax.swing.JButton();
        jDNuevo_Mensaje = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCBReceptor_Mensaje = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAMensaje = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jDBuzon_Salida = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jCBBuzon_Salida = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        arbolito2 = new javax.swing.JTree();
        jDNueva_Llamada = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jDLlamada = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLContacto = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCB_Llamada = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLDuracion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Crear Contacto");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        jLabel4.setText("Numero de Telefono:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Direccion:");

        jTFDireccion.setColumns(20);
        jTFDireccion.setRows(5);
        jScrollPane1.setViewportView(jTFDireccion);

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel7.setText("Genero:");

        jBGGen.add(jRBM);
        jRBM.setSelected(true);
        jRBM.setText("M");

        jBGGen.add(jRBF);
        jRBF.setText("F");

        javax.swing.GroupLayout jDCrear_ContactoLayout = new javax.swing.GroupLayout(jDCrear_Contacto.getContentPane());
        jDCrear_Contacto.getContentPane().setLayout(jDCrear_ContactoLayout);
        jDCrear_ContactoLayout.setHorizontalGroup(
            jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)
                        .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNombre))
                            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCorreo))
                            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFEdad))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNumero_Te)
                                    .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBF)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jDCrear_ContactoLayout.setVerticalGroup(
            jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jRBM)
                    .addComponent(jRBF))
                .addGap(18, 18, 18)
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFNumero_Te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDCrear_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jDCrear_ContactoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jDModificar_Contacto.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDModificar_ContactoWindowActivated(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Modificar Contacto");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Edad:");

        jLabel11.setText("Genero:");

        jBGGen.add(jRBM1);
        jRBM1.setText("M");

        jBGGen.add(jRBF1);
        jRBF1.setText("F");

        jLabel12.setText("Numero de Telefono:");

        jLabel13.setText("Correo:");

        jLabel14.setText("Direccion:");

        jTFDireccion1.setColumns(20);
        jTFDireccion1.setRows(5);
        jScrollPane2.setViewportView(jTFDireccion1);

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDModificar_ContactoLayout = new javax.swing.GroupLayout(jDModificar_Contacto.getContentPane());
        jDModificar_Contacto.getContentPane().setLayout(jDModificar_ContactoLayout);
        jDModificar_ContactoLayout.setHorizontalGroup(
            jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                        .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jCBModificar_Contacto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNombre1))
                            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCorreo1))
                            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFEdad1))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNumero_Te1)
                                    .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBM1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBF1)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jDModificar_ContactoLayout.setVerticalGroup(
            jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBModificar_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTFEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jRBM1)
                    .addComponent(jRBF1))
                .addGap(18, 18, 18)
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFNumero_Te1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDModificar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jDModificar_ContactoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jDEliminar_Contacto.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDEliminar_ContactoWindowActivated(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Eliminar Contacto");

        jButton3.setText("Eliminar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel16.setText("Nombre:");

        javax.swing.GroupLayout jDEliminar_ContactoLayout = new javax.swing.GroupLayout(jDEliminar_Contacto.getContentPane());
        jDEliminar_Contacto.getContentPane().setLayout(jDEliminar_ContactoLayout);
        jDEliminar_ContactoLayout.setHorizontalGroup(
            jDEliminar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDEliminar_ContactoLayout.createSequentialGroup()
                .addGroup(jDEliminar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDEliminar_ContactoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDEliminar_ContactoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBEliminar_Contacto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDEliminar_ContactoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        jDEliminar_ContactoLayout.setVerticalGroup(
            jDEliminar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDEliminar_ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jDEliminar_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jCBEliminar_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("Listar Contacto");

        jButton4.setText("Genero");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Contactos");
        arbolito.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(arbolito);

        jButton6.setText("Edad");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDAgenda_ContactoLayout = new javax.swing.GroupLayout(jDAgenda_Contacto.getContentPane());
        jDAgenda_Contacto.getContentPane().setLayout(jDAgenda_ContactoLayout);
        jDAgenda_ContactoLayout.setHorizontalGroup(
            jDAgenda_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDAgenda_ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDAgenda_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDAgenda_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDAgenda_ContactoLayout.setVerticalGroup(
            jDAgenda_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDAgenda_ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDAgenda_ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDAgenda_ContactoLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jDNuevo_Mensaje.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDNuevo_MensajeWindowActivated(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("Nuevo Mensaje");

        jLabel20.setText("Contacto:");

        jLabel21.setText("Mensaje:");

        jTAMensaje.setColumns(20);
        jTAMensaje.setRows(5);
        jScrollPane4.setViewportView(jTAMensaje);

        jButton5.setText("Enviar Mensaje");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDNuevo_MensajeLayout = new javax.swing.GroupLayout(jDNuevo_Mensaje.getContentPane());
        jDNuevo_Mensaje.getContentPane().setLayout(jDNuevo_MensajeLayout);
        jDNuevo_MensajeLayout.setHorizontalGroup(
            jDNuevo_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDNuevo_MensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDNuevo_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDNuevo_MensajeLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBReceptor_Mensaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDNuevo_MensajeLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );
        jDNuevo_MensajeLayout.setVerticalGroup(
            jDNuevo_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDNuevo_MensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jDNuevo_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jCBReceptor_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDNuevo_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jDBuzon_Salida.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDBuzon_SalidaWindowActivated(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setText("Buzon de Salida");

        jButton7.setText("Fecha");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Listar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mensajes");
        arbolito2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane7.setViewportView(arbolito2);

        javax.swing.GroupLayout jDBuzon_SalidaLayout = new javax.swing.GroupLayout(jDBuzon_Salida.getContentPane());
        jDBuzon_Salida.getContentPane().setLayout(jDBuzon_SalidaLayout);
        jDBuzon_SalidaLayout.setHorizontalGroup(
            jDBuzon_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDBuzon_SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDBuzon_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDBuzon_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jCBBuzon_Salida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDBuzon_SalidaLayout.setVerticalGroup(
            jDBuzon_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDBuzon_SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDBuzon_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDBuzon_SalidaLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jCBBuzon_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setText("Nueva Llamada");

        jLabel24.setText("Contacto:");

        jButton9.setText("Llamar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDNueva_LlamadaLayout = new javax.swing.GroupLayout(jDNueva_Llamada.getContentPane());
        jDNueva_Llamada.getContentPane().setLayout(jDNueva_LlamadaLayout);
        jDNueva_LlamadaLayout.setHorizontalGroup(
            jDNueva_LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDNueva_LlamadaLayout.createSequentialGroup()
                .addGroup(jDNueva_LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDNueva_LlamadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDNueva_LlamadaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDNueva_LlamadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(109, 109, 109))
        );
        jDNueva_LlamadaLayout.setVerticalGroup(
            jDNueva_LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDNueva_LlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jDNueva_LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jDLlamada.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDLlamadaWindowActivated(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Llamada");

        jLabel26.setText("Agregar Nuevo Contacto a la llamada");

        jButton10.setText("Agregar");

        jScrollPane6.setViewportView(jList2);

        jLabel25.setText("Contactos agregados en la llamada");

        jLabel27.setText("Duracion:");

        jLDuracion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLDuracion.setText("00:00");

        javax.swing.GroupLayout jDLlamadaLayout = new javax.swing.GroupLayout(jDLlamada.getContentPane());
        jDLlamada.getContentPane().setLayout(jDLlamadaLayout);
        jDLlamadaLayout.setHorizontalGroup(
            jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDLlamadaLayout.createSequentialGroup()
                .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDLlamadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDLlamadaLayout.createSequentialGroup()
                                .addComponent(jLContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jDLlamadaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_Llamada, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDLlamadaLayout.setVerticalGroup(
            jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addComponent(jLDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDLlamadaLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Llamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Contacto");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem4.setText("Agenda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenu3.setText("Mensaje");

        jMenuItem5.setText("Nuevo Mensaje");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Buzon de Salida");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenu2.add(jMenu3);

        jMenu4.setText("Llamada");

        jMenuItem7.setText("Nueva Llamada");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Nueva Video Llamada");
        jMenu4.add(jMenuItem8);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       jDCrear_Contacto.setModal(true);
       jDCrear_Contacto.pack();
       jDCrear_Contacto.setLocationRelativeTo(this);
       jDCrear_Contacto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Dba db = new Dba("./Database1.accdb");
        db.conectar();
        try {
            String gen = "";
            if (jRBM.isSelected()) {
                gen = "Masculino";
            } else {
                gen = "Femenino";
            }
            Contacto c = new Contacto(jTFNombre.getText(), Integer.parseInt(jTFNumero_Te.getText()), Integer.parseInt(jTFEdad.getText()), jTFCorreo.getText(), jTFDireccion.getText(), gen);
            db.query.execute("INSERT INTO contactos"
                    + " (nombre, numero_telefono, edad, correo, direccion, genero)"
                    + " VALUES('" + c.getNombre() + "','" + c.getEdad() + "','" + c.getNum_tel() + "','" + c.getCorreo() + "','" +  c.getDireccion() + "','" + c.getGen() + "')");
            db.commit();
            JOptionPane.showMessageDialog(jDCrear_Contacto, "Contacto Creado");
            jTFNombre.setText("");
            jTFNumero_Te.setText("");
            jTFEdad.setText("");
            jTFCorreo.setText("");
            jTFDireccion.setText("");
            jRBM1.setSelected(true);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jDModificar_Contacto.setModal(true);
        jDModificar_Contacto.pack();
        jDModificar_Contacto.setLocationRelativeTo(this);
        jDModificar_Contacto.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Dba db = new Dba("./Database1.accdb");
        db.conectar();
        String gen = "";
        if (jRBM1.isSelected()) {
            gen = "Masculino";
        } else {
            gen = "Femenino";
        }
        try {
            db.query.execute("update contactos set nombre='" + jTFNombre1.getText() + "',numero_telefono='" + jTFNumero_Te1.getText() + "',edad='" + jTFEdad1.getText() + "',correo='" + jTFCorreo1.getText() + "',direccion='" + jTFDireccion1.getText() + "',genero='" + gen + "'where nombre='" + jCBModificar_Contacto.getSelectedItem().toString() + "'");
            db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDEliminar_Contacto.setModal(true);
        jDEliminar_Contacto.pack();
        jDEliminar_Contacto.setLocationRelativeTo(this);
        jDEliminar_Contacto.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Dba db = new Dba("./Database1.accdb");
        db.conectar();
        try {
            db.query.execute("delete from contactos where nombre='" + jCBEliminar_Contacto.getSelectedItem().toString() + "'");
            db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Dba db = new Dba("./Database1.accdb");
        DefaultTreeModel modelo = (DefaultTreeModel) arbolito.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        arbolito.removeAll();
        db.conectar();
        int centinela = -1;
        try {
            db.query.execute("select * from contactos");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(rs.getString(6))) {
                        //Si ya Existe le Agrega la Persona
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Contacto(rs.getString(1), rs.getInt(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6)));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(rs.getString(6));
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Contacto(rs.getString(1), rs.getInt(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6)));
                    n.add(p);
                    raiz.add(n);
                }
                modelo.reload();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jDModificar_ContactoWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDModificar_ContactoWindowActivated
        if (jDModificar_Contacto.isActive()) {
            Dba db = new Dba("./Database1.accdb");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCBModificar_Contacto.getModel();
            db.conectar();
            modelo.removeAllElements();
            try {
                db.query.execute("select nombre from contactos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                    jCBModificar_Contacto.setModel(modelo);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_jDModificar_ContactoWindowActivated

    private void jDEliminar_ContactoWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDEliminar_ContactoWindowActivated
        if (jDEliminar_Contacto.isActive()) {
            Dba db = new Dba("./Database1.accdb");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCBEliminar_Contacto.getModel();
            db.conectar();
            modelo.removeAllElements();
            try {
                db.query.execute("select nombre from contactos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                    jCBEliminar_Contacto.setModel(modelo);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_jDEliminar_ContactoWindowActivated

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jDAgenda_Contacto.setModal(true);
        jDAgenda_Contacto.pack();
        jDAgenda_Contacto.setLocationRelativeTo(this);
        jDAgenda_Contacto.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Dba db = new Dba("./Database1.accdb");
        DefaultTreeModel modelo = (DefaultTreeModel) arbolito.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        arbolito2.removeAll();
        db.conectar();
        int centinela = -1;
        try {
            db.query.execute("select * from contactos");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (Integer.parseInt(raiz.getChildAt(i).toString()) == rs.getInt(2)) {
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Contacto(rs.getString(1), rs.getInt(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6)));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(rs.getInt(2));
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Contacto(rs.getString(1), rs.getInt(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6)));
                    n.add(p);
                    raiz.add(n);
                }
                modelo.reload();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Dba db = new Dba("./Database1.accdb");
        db.conectar();
        try {
            Date fecha = new Date();
            DateFormat df = new SimpleDateFormat("yyyy//MM//dd");
            String fecha2=df.format(fecha);
            db.query.execute("INSERT INTO mensaje"
                    + "(emisor,receptor,fecha_envio,contenido)"
                    + "VALUES ('" + admin.getNombre() + "','" + jCBReceptor_Mensaje.getSelectedItem().toString() + "','" + fecha2 + "','" + jTAMensaje.getText() + "')");
           db.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jDNuevo_Mensaje.setModal(true);
        jDNuevo_Mensaje.pack();
        jDNuevo_Mensaje.setLocationRelativeTo(this);
        jDNuevo_Mensaje.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Dba db = new Dba("./Database1.accdb");
        DefaultTreeModel modelo = (DefaultTreeModel) arbolito2.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        arbolito2.removeAll();
        db.conectar();
        int centinela = -1;
        try {
            db.query.execute("select * from mensaje");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(rs.getString(2))) {
                        //Si ya Existe le Agrega la Persona
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(rs.getString(3));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(rs.getString(2));
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(rs.getString(3));
                    n.add(p);
                    raiz.add(n);
                }
                modelo.reload();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jDNuevo_MensajeWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDNuevo_MensajeWindowActivated
       if (jDNuevo_Mensaje.isActive()) {
            Dba db = new Dba("./Database1.accdb");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCBReceptor_Mensaje.getModel();
            db.conectar();
            modelo.removeAllElements();
            try {
                db.query.execute("select nombre from contactos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                    jCBReceptor_Mensaje.setModel(modelo);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_jDNuevo_MensajeWindowActivated

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jDBuzon_Salida.setModal(true);
        jDBuzon_Salida.pack();
        jDBuzon_Salida.setLocationRelativeTo(this);
        jDBuzon_Salida.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jDBuzon_SalidaWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDBuzon_SalidaWindowActivated
        if (jDBuzon_Salida.isActive()) {
            Dba db = new Dba("./Database1.accdb");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jCBBuzon_Salida.getModel();
            db.conectar();
            modelo.removeAllElements();
            try {
                db.query.execute("select nombre from contactos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                    jCBBuzon_Salida.setModel(modelo);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_jDBuzon_SalidaWindowActivated

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
       Dba db = new Dba("./Database1.accdb");
        DefaultTreeModel modelo = (DefaultTreeModel) arbolito2.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        arbolito2.removeAll();
        db.conectar();
        int centinela = -1;
        try {
            db.query.execute("select * from mensaje");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(rs.getString(4))) {
                        //Si ya Existe le Agrega la Persona
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(rs.getString(3));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(rs.getString(4));
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(rs.getString(3));
                    n.add(p);
                    raiz.add(n);
                }
                modelo.reload();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jDLlamadaWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDLlamadaWindowActivated
        if (jDLlamada.isActive()) {
            Duracion_Llamada DLl = new Duracion_Llamada(jLDuracion);
            DLl.start();
        }
    }//GEN-LAST:event_jDLlamadaWindowActivated

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jDNueva_Llamada.setModal(true);
        jDNueva_Llamada.pack();
        jDNueva_Llamada.setLocationRelativeTo(this);
        jDNueva_Llamada.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        jDLlamada.setModal(true);
        jDLlamada.pack();
        jDLlamada.setLocationRelativeTo(this);
        jDLlamada.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolito;
    private javax.swing.JTree arbolito2;
    private javax.swing.ButtonGroup jBGGen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCBBuzon_Salida;
    private javax.swing.JComboBox<String> jCBEliminar_Contacto;
    private javax.swing.JComboBox<String> jCBModificar_Contacto;
    private javax.swing.JComboBox<String> jCBReceptor_Mensaje;
    private javax.swing.JComboBox<String> jCB_Llamada;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDAgenda_Contacto;
    private javax.swing.JDialog jDBuzon_Salida;
    private javax.swing.JDialog jDCrear_Contacto;
    private javax.swing.JDialog jDEliminar_Contacto;
    private javax.swing.JDialog jDLlamada;
    private javax.swing.JDialog jDModificar_Contacto;
    private javax.swing.JDialog jDNueva_Llamada;
    private javax.swing.JDialog jDNuevo_Mensaje;
    private javax.swing.JLabel jLContacto;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButton jRBF;
    private javax.swing.JRadioButton jRBF1;
    private javax.swing.JRadioButton jRBM;
    private javax.swing.JRadioButton jRBM1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTAMensaje;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFCorreo1;
    private javax.swing.JTextArea jTFDireccion;
    private javax.swing.JTextArea jTFDireccion1;
    private javax.swing.JTextField jTFEdad;
    private javax.swing.JTextField jTFEdad1;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNumero_Te;
    private javax.swing.JTextField jTFNumero_Te1;
    // End of variables declaration//GEN-END:variables
    Contacto admin = new Contacto("admin", 96900525, 20, "guillendiazd@outlook.com", "Col. Bella Oriente", "Madculino");
}
